; FEELTECHWear Network Configuration
; このファイルを SD カードのルートに "network.ini" として配置してください。
; 記載しない項目は sdkconfig のデフォルト値が使われます。

[mode]
type = wifi       ; wifi または ethernet
role = ap         ; ap または sta

[wifi_ap]
ssid     = FTW_DEVICE
password = FTW_PSWD
channel  = 1
max_sta  = 4

[wifi_sta]
ssid     = Target SSID
password = Target Password

[network_ap]
ipv4_addr    = 192.168.4.1
ipv4_mask    = 255.255.255.0
ipv4_gateway = 192.168.4.1

[mdns]
hostname = ftw-device

[udp]
port = 3333

[browser_update]
enabled  = false      ; true または false
password = ftw-update
